### ISSUE TITLE
Unable to compile in Linux Mint 19.2

### ISSUE THREAD

**Issue by pc-magas** [fanisatt/EORTOLOGIO-GR#1]
I tried:
```
$ gcc -c geortes2.c -lSDL_bgi -lSDL2
```

But fails to build:

```
geortes2.c:8:9: fatal error: graphics.h: Δεν υπάρχει τέτοιο αρχείο ή κατάλογος
 #include<graphics.h>
         ^~~~~~~~~~~~
compilation terminated.

```

In order to resolve it I tried ` sudo apt-get install libsdl2-image-2.0-0 ` and ` sudo apt-get install libsdl2-image-dev` before retrying to compile still I am getting this error.

**Comment by fanisatt** [comment]
https://sourceforge.net/projects/eortologio-gr/
Read the instructions in Greek....
